const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

/**
 * Extract frames from a YouTube video using Python OpenCV
 * @param {string} youtubeUrl - The YouTube video URL
 * @param {string} uniqueId - The unique ID generated by Node.js to use for this video
 * @returns {Promise<Object>} Result object with frames info
 */
async function extractFramesFromYouTube(youtubeUrl, uniqueId) {
  return new Promise((resolve, reject) => {
    console.log(`Starting frame extraction for ${youtubeUrl} using Python (ID: ${uniqueId})`);
    
    const pythonScript = path.join(__dirname, '..', 'extract_frames.py');
    console.log(`Using Python script at: ${pythonScript}`);
    
    // Make sure the script exists
    if (!fs.existsSync(pythonScript)) {
      return reject(new Error(`Python script not found at ${pythonScript}`));
    }
    
    // Validate uniqueId
    if (!uniqueId) {
      return reject(new Error('Unique ID must be provided to extractFramesFromYouTube'));
    }
    
    // Run the Python script, passing youtubeUrl and uniqueId
    const process = spawn('python', [pythonScript, youtubeUrl, uniqueId]);
    
    let outputData = '';
    let errorData = '';
    
    // Collect data from script
    process.stdout.on('data', (data) => {
      outputData += data.toString();
      console.log(`Python output: ${data.toString().trim()}`);
    });
    
    process.stderr.on('data', (data) => {
      errorData += data.toString();
      console.error(`Python error: ${data.toString().trim()}`);
    });
    
    // Handle completion
    process.on('close', (code) => {
      log_stderr(`Python process exited with code ${code} for ID ${uniqueId}`);
      
      // Check exit code first
      if (code !== 0) {
        // If error code, reject with the stderr output
        const errorMessage = errorData.trim() || `Python script failed with exit code ${code}`;
        log_stderr(`Python script error (code ${code}) for ID ${uniqueId}: ${errorMessage}`);
        return reject(new Error(errorMessage));
      }
      
      // If exit code is 0, process stdout for JSON
      try {
        const output = outputData.trim();
        if (!output) {
          // Handle cases where the script exits successfully but with no output
          log_stderr(`Python script for ID ${uniqueId} exited successfully but produced no stdout.`);
          return reject(new Error('Python script produced no output despite success exit code.'));
        }

        const result = JSON.parse(output); // Parse the entire stdout
        log_stderr(`Successfully parsed Python JSON output for ID ${uniqueId}`);
        // console.log(`Python script result for ${uniqueId}:`, result); // Keep if verbose logging is desired
        
        // Optional: Verify the returned video_id matches the sent uniqueId
        if (result.video_id && result.video_id !== uniqueId) {
            console.warn(`Warning: Python script returned video_id ${result.video_id} which differs from the requested uniqueId ${uniqueId}. Using requested ID.`);
            result.video_id = uniqueId; // Ensure consistency
        }
        
        resolve(result);
      } catch (error) {
         // JSON parsing failed
        log_stderr(`Failed to parse Python stdout for ID ${uniqueId}. Error: ${error.message}`);
        log_stderr(`Raw stdout for ID ${uniqueId}:\n${outputData}`); // Log raw output for debugging
        reject(new Error(`Failed to parse JSON output from Python script: ${error.message}`));
      }
    });
    
    // Handle errors spawning the process
    process.on('error', (error) => {
      log_stderr(`Failed to start Python process for ID ${uniqueId}: ${error.message}`);
      reject(new Error(`Failed to start Python process: ${error.message}`));
    });
  });
}

// Helper log function (optional, can use console.error directly)
function log_stderr(message) {
    console.error(`[FrameExtractor] ${message}`);
}

module.exports = { extractFramesFromYouTube }; 